import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <meta name="description" content="Softwareentwickler mit Fokus auf Fullstack-Lösungen." />
      <meta property="og:title" content="Michael Reischl - Portfolio" />
      <meta property="og:description" content="Erfahre mehr über meine Projekte und Skills." />
      <meta property="og:image" content="/favicon.ico" />
      <link rel="icon" href="/favicon.ico"></link>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
